# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('ISO', 'ISO 9001'), ('API', 'API 6D and 6A'), ('PED', 'PED'), ('DNV', 'DNV'), ('EAC', 'Russian Certification'), ('ABS', 'ABS'), ('Cust', 'Customer audit')], max_length=4)),
                ('audit_regulation', models.CharField(choices=[('ISO', 'ISO 9001:2015'), ('API', 'API 6D, 6A, Q1, 607'), ('PED', 'EU 2014/68'), ('Cust', 'Customer specification')], max_length=4)),
            ],
        ),
    ]
