# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(max_length=10)),
                ('section_heading', models.CharField(max_length=50)),
                ('audit_type_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.AuditType')),
            ],
        ),
    ]
