# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auditsections'),
    ]

    operations = [
        migrations.AddField(
            model_name='audittype',
            name='type_title',
            field=models.CharField(default=111, max_length=50),
            preserve_default=False,
        ),
    ]
