# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_auditquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditquestions',
            name='section_num',
            field=models.CharField(max_length=20, verbose_name='section no.'),
        ),
    ]
