# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_auto_20170213_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditquestions',
            name='audit_guidance',
            field=models.TextField(blank=True, verbose_name='audit guide'),
        ),
        migrations.AlterField(
            model_name='auditquestions',
            name='audit_specific',
            field=models.TextField(blank=True, verbose_name='audit specific question'),
        ),
        migrations.AlterField(
            model_name='auditquestions',
            name='general_question',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditquestions',
            name='subsection_num',
            field=models.CharField(blank=True, max_length=20, verbose_name='sub-section no.'),
        ),
        migrations.AlterField(
            model_name='auditquestions',
            name='subsection_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='sub-section'),
        ),
    ]
