# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_auditcomments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditcomments',
            options={'verbose_name': 'Audit Comments', 'verbose_name_plural': 'Audit Comments'},
        ),
        migrations.AddField(
            model_name='auditcomments',
            name='comment_text',
            field=models.TextField(default='99'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditcomments',
            name='comment_title',
            field=models.CharField(default='99', max_length=200),
            preserve_default=False,
        ),
    ]
