# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StandardWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=200)),
                ('work_frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('B', 'Bi-Monthly (2x Mo.)'), ('M', 'Monthly'), ('Q', 'Quarterly'), ('Y', 'Yearly')], max_length=1)),
                ('work_last_dt', models.DateField()),
                ('work_next_dt', models.DateField()),
            ],
        ),
    ]
