# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard_work', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standardwork',
            options={'verbose_name': 'Standard work', 'verbose_name_plural': 'Standard work'},
        ),
        migrations.AlterField(
            model_name='standardwork',
            name='work_last_dt',
            field=models.DateField(blank=True, null=True, verbose_name='last date'),
        ),
        migrations.AlterField(
            model_name='standardwork',
            name='work_next_dt',
            field=models.DateField(blank=True, null=True, verbose_name='next sched date'),
        ),
    ]
