# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('standard_work', '0003_auto_20170212_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workguidance',
            options={'verbose_name': 'Work guidance', 'verbose_name_plural': 'Work guidance'},
        ),
        migrations.AlterModelOptions(
            name='workremarks',
            options={'verbose_name': 'Records', 'verbose_name_plural': 'Records'},
        ),
        migrations.AddField(
            model_name='workremarks',
            name='remark_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
