# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard_work', '0004_auto_20170212_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workguidance',
            name='id',
        ),
        migrations.AlterField(
            model_name='workguidance',
            name='guide_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='standard_work.StandardWork'),
        ),
    ]
