# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard_work', '0007_auto_20170212_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='workguidance',
            name='id',
            field=models.AutoField(auto_created=True, default=99, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workguidance',
            name='guide_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standard_work.StandardWork'),
        ),
    ]
