# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_title', models.CharField(max_length=200)),
                ('incident_text', models.TextField()),
                ('incident_contact', models.CharField(max_length=200)),
                ('incident_dt', models.DateTimeField()),
                ('resolution_dt', models.DateTimeField(blank=True, null=True)),
                ('root_cause', models.TextField()),
                ('steps_to_fix', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
