# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_auto_20170214_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidents',
            name='resolved_time',
            field=models.IntegerField(default=999, verbose_name='duration (in seconds)'),
            preserve_default=False,
        ),
    ]
